spring.application.name=AmmavariGudiService
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/demoapplication
spring.datasource.username=root
spring.datasource.password=sivaT123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret: myVerySecretKeyForJwtGeneration123456789
jwt.expiration: 3600000